name: RSS Feed to Notion

on:
  # Run daily at 1 AM UTC
  schedule:
    - cron: '0 0 * * *'
  
  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  sync-rss-to-notion:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python 3.12.1
      - name: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create config.json from secrets
      - name: Create config.json
        env:
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
        run: echo $CONFIG_JSON > config.json

      # Run the script
      - name: Run the script
        run: |
          python feed_to_notion.py
